export const USER_LOGIN_REQUSET =  'USER_LOGIN_REQUSET'
export const USER_LOGIN_SUCCESS =  'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL =  'USER_LOGIN_FAIL'
export const USER_LOGOUT =  'USER_LOGOUT'


export const USER_REGISTER_REQUSET =  'USER_REGISTER_REQUSET'
export const USER_REGISTER_SUCCESS =  'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL =  'USER_REGISTER_FAIL'


export const USER_DETAILS_REQUSET =  'USER_DETAILS_REQUSET'
export const USER_DETAILS_SUCCESS =  'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL =  'USER_DETAILS_FAIL'


export const USER_UPDATE_PROFILE_REQUSET =  'USER_UPDATE_PROFILE_REQUSET'
export const USER_UPDATE_PROFILE_SUCCESS =  'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL =  'USER_UPDATE_PROFILE_FAIL'


